version: "3"
services:
  db:
    image: mysql:8.0.33
    volumes:
      - lypa-mysql-data:/var/lib/mysql
      - ./initTables.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: lypadb
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=
      - DB_HOST=db
      - DB_USERNAME=root 
      - DB_PASSWORD=admin 
      - DB_DATABASE=lypadb
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  lypa-mysql-data: